/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'server',
    path: '/server',
    // @ts-expect-error elegant-router generated types don't fully support parent routes with children
    component: 'layout.base',
    meta: {
      title: 'server',
      i18nKey: 'route.server',
      icon: 'mdi:server',
      order: 2
    },
    children: [
      {
        name: 'server_all-servers',
        path: '/server/all-servers',
        component: 'view.server_all-servers',
        meta: {
          title: 'server_all-servers',
          i18nKey: 'route.server_all-servers',
          icon: 'mdi:server-network'
        }
      },
      {
        name: 'server_metrics',
        path: '/server/metrics',
        component: 'view.server_metrics',
        meta: {
          title: 'server_metrics',
          i18nKey: 'route.server_metrics',
          icon: 'mdi:chart-line'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    // @ts-expect-error elegant-router generated types don't fully support parent routes with children
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'carbon:settings',
      order: 3
    },
    children: [
      {
        name: 'system_individual',
        path: '/system/individual',
        component: 'view.system_individual',
        meta: {
          title: 'system_individual',
          i18nKey: 'route.system_individual',
          icon: 'mdi:palette'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user',
          icon: 'mdi:account-group'
        }
      }
    ]
  }
];
